### ISSUE TITLE
corly-import.py: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by petr-muller** [FilipMatys/ResultCloud#48]
When I try to submit results to Corly (against hele.fit.vutbr.cz instance) using the import script, I get the following traceback:

$ ./corly-import.py  muller <snipped> 3 1 ../../systemtap/testsuite/systemtap.sum 
Traceback (most recent call last):
  File "./corly-import.py", line 46, in <module>
    if user.auth(user_name, password):
  File "/home/afri/Projects/IBP2013/scripts/corlyapi.py", line 15, in auth
    resp = self.send_request("auth", "login", {"username": username, "password": password})
  File "/home/afri/Projects/IBP2013/scripts/corlyapi.py", line 45, in send_request
    resp = json.loads(requests.get(request).text)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by petr-muller** [comment]
This is related to the production/test instance split. First, I needed to change the API url to the production one:

http://hele.fit.vutbr.cz/~xmatys10/production/method/

But even then, this URL is (wrongly) rewritten to ~xmatys10/api/MethodController.class.php:
http://hele.fit.vutbr.cz/~xmatys10/production/method/auth.login
